-- +migrate Up
CREATE TABLE IF NOT EXISTS `store` (
  `store_id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `store_name` VARCHAR(255) NOT NULL,
  `store_email` VARCHAR(255) NOT NULL,
  `store_phone_number` VARCHAR(255) NOT NULL,
  `encrypted_password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +migrate Down
DROP TABLE IF EXISTS `store`;
